### ISSUE TITLE
Can't accept misspelled answer

### ISSUE THREAD

**Issue by AmbrusIttzes** [pAlkesz/mr-x#14]
![IMG_2885](https://github.com/user-attachments/assets/85e1d6b0-6777-427c-9ab3-4e1800e4d933)

ez egy jó válasz, rá megyek h accept erre azt akarja h kérdezzek tovább

**Comment by pAlkesz** [comment]
Hat ugye nem találta el a host a választ....szoval ez kicsit user error.....megcsinalhatnam h a question owner elfogadhatja teljesen a host válaszát de nem tudom kell-e ez tényleg
