### ISSUE TITLE
Change question placeholders for host

### ISSUE THREAD

**Issue by AmbrusIttzes** [pAlkesz/mr-x#2]
![IMG_2881](https://github.com/user-attachments/assets/4cf497d4-34f8-4aa6-bee1-00320382449c)

itt olyan mintha én is szerethetnék barkhoba kérdéseket, kéne egy másik szöveg ide ha én vagyok a host

**Comment by AmbrusIttzes** [comment]
*szerezhetnék

**Comment by pAlkesz** [comment]
Igen erre en is gondoltam, de lusta voltam eddig megcsinalni. Hamarosan fixalom, stay tuned
